export type ProductCategory =
  | "watches"
  | "ppe"
  | "tech"
  | "acrylic"
  | "silicone"
  | "lanyards"
  | "sunglasses"
  | "drinkware"
  | "apparel"
  | "emblems"
  | "office"
  | "cannabis"
  | "packaging"
  | "other";

export interface Product {
  slug: string;
  sku: string;
  name: string;
  category: ProductCategory;
}

export interface CategoryMeta {
  key: ProductCategory;
  label: string;
  inNav: boolean;
}

export const CATEGORIES: CategoryMeta[] = [
  { key: "ppe", label: "PPE", inNav: true },
  { key: "tech", label: "Smartphone & Tech Accessories", inNav: true },
  { key: "acrylic", label: "Acrylic Products", inNav: true },
  { key: "silicone", label: "Silicon Awareness", inNav: true },
  { key: "watches", label: "Watches", inNav: true },
  { key: "lanyards", label: "Lanyards & Hairties", inNav: true },
  { key: "sunglasses", label: "Sunglasses", inNav: false },
  { key: "drinkware", label: "Drinkware & Bar", inNav: false },
  { key: "apparel", label: "Apparel & Bags", inNav: false },
  { key: "emblems", label: "Emblematic Metals", inNav: false },
  { key: "office", label: "Office & Stationery", inNav: false },
  { key: "cannabis", label: "Cannabis Supply", inNav: false },
  { key: "packaging", label: "Custom Packaging", inNav: false },
  { key: "other", label: "Other", inNav: false },
];

export const CATEGORY_LABEL: Record<ProductCategory, string> =
  CATEGORIES.reduce(
    (acc, c) => {
      acc[c.key] = c.label;
      return acc;
    },
    {} as Record<ProductCategory, string>,
  );

export const NAV_PRODUCT_CATEGORIES = CATEGORIES.filter((c) => c.inNav);

export function productUrl(p: Product): string {
  return `https://www.timezoneus.com/product/${p.slug}/${encodeURIComponent(
    p.sku.toLowerCase(),
  )}`;
}

export const PRODUCTS: Product[] = [
  {"slug":"4-color-process-plastic-watch","sku":"1904CP","name":"4 Color Process Plastic Watch","category":"watches"},
  {"slug":"all-silver-watch","sku":"716S","name":"All Silver Watch","category":"watches"},
  {"slug":"analog-carabiner-clip-union-watch","sku":"UTZCO-04","name":"Analog Carabiner Clip Union Watch","category":"watches"},
  {"slug":"blue-carabiner-clip-watch","sku":"152-8","name":"Blue Carabiner Clip Watch","category":"watches"},
  {"slug":"blue-or-black-bezel-clip-watch","sku":"152-8LCD","name":"Blue Or Black Bezel Clip Watch","category":"watches"},
  {"slug":"brushed-silver-case-with-black-padded-leather-band","sku":"263","name":"Brushed Silver Case With Black Padded Leather Band","category":"watches"},
  {"slug":"carabiner-clip-watch-with-compass-and-bottle-opener","sku":"TZCO-04","name":"Carabiner Clip Watch With Compass And Bottle Opener","category":"watches"},
  {"slug":"custom-dipper-watch","sku":"TZ-DW","name":"Custom Dipper Watch","category":"watches"},
  {"slug":"gold-case-with-black-padded-leather-band","sku":"260","name":"Gold Case With Black Padded Leather Band","category":"watches"},
  {"slug":"gold-case-with-black-padded-leather-band","sku":"130G","name":"Gold Case With Black Padded Leather Band","category":"watches"},
  {"slug":"gold-case-with-black-padded-leather-band","sku":"135G","name":"Gold Case With Black Padded Leather Band","category":"watches"},
  {"slug":"gold-case-with-black-padded-leather-band","sku":"129G","name":"Gold Case With Black Padded Leather Band","category":"watches"},
  {"slug":"gold-clip-watch","sku":"290-7G","name":"Gold Clip Watch","category":"watches"},
  {"slug":"gold-or-silver-case-with-leather-band","sku":"TZTOC","name":"Gold Or Silver Case With Leather Band","category":"watches"},
  {"slug":"gold-rectangle-shaped-case-with-leather-band","sku":"DLUX252","name":"Gold Rectangle Shaped Case With Leather Band","category":"watches"},
  {"slug":"gold-swiss-style-union-watch","sku":"U142","name":"Gold Swiss Style Union Watch","category":"watches"},
  {"slug":"gold-swiss-style-watch","sku":"142","name":"Gold Swiss Style Watch","category":"watches"},
  {"slug":"gold-union-watch-with-leather-band","sku":"U130G","name":"Gold Union Watch With Leather Band","category":"watches"},
  {"slug":"gold-watch-with-die-struck-medallion-face-black-padded-leather-band","sku":"130USAM","name":"Gold Watch With Die Struck Medallion Face Black Padded Leather Band","category":"watches"},
  {"slug":"gold-watch-with-expansion-band","sku":"276GTW","name":"Gold Watch With Expansion Band","category":"watches"},
  {"slug":"gold-watch-with-expansion-band","sku":"260GTW","name":"Gold Watch With Expansion Band","category":"watches"},
  {"slug":"gold-watch-with-gold-band","sku":"292G","name":"Gold Watch With Gold Band","category":"watches"},
  {"slug":"lcd-carabiner-clip-union-watch","sku":"UTZCO-LCD","name":"LCD Carabiner Clip Union Watch","category":"watches"},
  {"slug":"plastic-watch","sku":"190","name":"Plastic Watch","category":"watches"},
  {"slug":"rectangle-union-watch","sku":"U250S","name":"Rectangle Union Watch","category":"watches"},
  {"slug":"roman-numeral-case-union-watch","sku":"U591G","name":"Roman Numeral Case Union Watch","category":"watches"},
  {"slug":"roman-numeral-on-the-gold-case-with-black-padded-leather-band","sku":"239G","name":"Roman Numeral On The Gold Case With Black Padded Leather Band","category":"watches"},
  {"slug":"roman-numeral-on-the-silver-case-with-black-padded-leather-band","sku":"239S","name":"Roman Numeral On The Silver Case With Black Padded Leather Band","category":"watches"},
  {"slug":"silver-bezel-with-black-padded-leather-band","sku":"293","name":"Silver Bezel With Black Padded Leather Band","category":"watches"},
  {"slug":"silver-carabiner-clip-watch-with-compass-and-bottle-opener","sku":"TZCO-LCD","name":"Silver Carabiner Clip Watch With Compass And Bottle Opener","category":"watches"},
  {"slug":"silver-case-with-black-padded-leather-band","sku":"135","name":"Silver Case With Black Padded Leather Band","category":"watches"},
  {"slug":"silver-case-with-black-padded-leather-band","sku":"128S","name":"Silver Case With Black Padded Leather Band","category":"watches"},
  {"slug":"silver-case-with-black-padded-leather-band","sku":"130S","name":"Silver Case With Black Padded Leather Band","category":"watches"},
  {"slug":"silver-case-with-black-padded-leather-band","sku":"129S","name":"Silver Case With Black Padded Leather Band","category":"watches"},
  {"slug":"silver-clip-watch","sku":"151-7LCD","name":"Silver Clip Watch","category":"watches"},
  {"slug":"silver-clip-watch","sku":"290-7S","name":"Silver Clip Watch","category":"watches"},
  {"slug":"silver-rectangle-shaped-case-with-alligator-leather-band","sku":"250S","name":"Silver Rectangle Shaped Case With Alligator Leather Band","category":"watches"},
  {"slug":"silver-rectangle-shaped-case-withblack-padded-leather-band","sku":"TZT021S","name":"Silver Rectangle Shaped Case Withblack Padded Leather Band","category":"watches"},
  {"slug":"silver-union-watch","sku":"U716S","name":"Silver Union Watch","category":"watches"},
  {"slug":"silver-union-watch-with-leather-band","sku":"U716","name":"Silver Union Watch With Leather Band","category":"watches"},
  {"slug":"silver-watch-with-etched-medallion-face-and-black-padded-leather-band","sku":"293IM","name":"Silver Watch With Etched Medallion Face And Black Padded Leather Band","category":"watches"},
  {"slug":"silver-watch-with-etched-medallion-face-black-padded-leather-band","sku":"130IM","name":"Silver Watch With Etched Medallion Face Black Padded Leather Band","category":"watches"},
  {"slug":"silver-watch-with-silver-band","sku":"291S","name":"Silver Watch With Silver Band","category":"watches"},
  {"slug":"two-tone-case-with-black-leather-band","sku":"295","name":"Two Tone Case With Black Leather Band","category":"watches"},
  {"slug":"two-tone-case-with-black-padded-leather-band","sku":"262","name":"Two Tone Case With Black Padded Leather Band","category":"watches"},
  {"slug":"two-tone-case-with-brown-alligator-leather-band","sku":"595","name":"Two Tone Case With Brown Alligator Leather Band","category":"watches"},
  {"slug":"two-tone-swiss-style-union-watch","sku":"U140","name":"Two Tone Swiss Style Union Watch","category":"watches"},
  {"slug":"two-tone-swiss-style-watch-with-carbon-fiber-dial","sku":"1140CZ","name":"Two Tone Swiss Style Watch With Carbon Fiber Dial","category":"watches"},
  {"slug":"two-tone-twist-band-union-watch","sku":"U266","name":"Two Tone Twist Band Union Watch","category":"watches"},
  {"slug":"two-tone-union-watch","sku":"U291G","name":"Two Tone Union Watch","category":"watches"},
  {"slug":"two-tone-union-watch","sku":"U268","name":"Two Tone Union Watch","category":"watches"},
  {"slug":"two-tone-watch","sku":"591","name":"Two Tone Watch","category":"watches"},
  {"slug":"two-tone-watch","sku":"1140","name":"Two Tone Watch","category":"watches"},
  {"slug":"two-tone-watch","sku":"291G","name":"Two Tone Watch","category":"watches"},
  {"slug":"two-tone-watch-w-date-calendar","sku":"140","name":"Two Tone Watch w/ Date Calendar","category":"watches"},
  {"slug":"two-tone-watch-with-die-struck-medallion-face","sku":"291USAM","name":"Two Tone Watch With Die Struck Medallion Face","category":"watches"},
  {"slug":"two-tone-watch-with-expansion-band","sku":"266","name":"Two Tone Watch With Expansion Band","category":"watches"},
  {"slug":"4-ply-face-mask","sku":"TZ-4PCM-DS","name":"4 Ply Face Mask","category":"ppe"},
  {"slug":"95-bfe-filtration-mask","sku":"TZ-MASK2-95","name":"95 Bfe Filtration Mask","category":"ppe"},
  {"slug":"anti-germ-tool","sku":"TZ-AGT","name":"Anti Germ Tool","category":"ppe"},
  {"slug":"anti-germ-tool","sku":"TZ-AGT-ABS","name":"Anti Germ Tool","category":"ppe"},
  {"slug":"body-bag","sku":"TZ-PPE-BB","name":"Body Bag","category":"ppe"},
  {"slug":"colored-cotton-mask","sku":"TZ-4PCM-CC","name":"Colored Cotton Mask","category":"ppe"},
  {"slug":"colored-disposable-mask","sku":"TZ-MASK2-95-SC","name":"Colored Disposable Mask","category":"ppe"},
  {"slug":"cotton-mask","sku":"TZ-4PCM","name":"Cotton Mask","category":"ppe"},
  {"slug":"cotton-mask-with-adjustable-ear-loop","sku":"TZ-3PCM-AEL","name":"Cotton Mask With Adjustable Ear Loop","category":"ppe"},
  {"slug":"desktop-viral-shield","sku":"TZ-VSH24","name":"Desktop Viral Shield","category":"ppe"},
  {"slug":"digital-thermometer","sku":"TZ-PPE-DT","name":"Digital Thermometer","category":"ppe"},
  {"slug":"disposable-mask","sku":"TZ-MASK2","name":"Disposable Mask","category":"ppe"},
  {"slug":"face-shield","sku":"TZ-FS","name":"Face Shield","category":"ppe"},
  {"slug":"face-shield-with-frame","sku":"TZ-FS2-GF","name":"Face Shield With Frame","category":"ppe"},
  {"slug":"hand-sanitizer","sku":"TZ-HS","name":"Hand Sanitizer","category":"ppe"},
  {"slug":"hand-sanitizer-stand","sku":"TZ-HSS","name":"Hand Sanitizer Stand","category":"ppe"},
  {"slug":"kids-disposable-mask","sku":"TZ-MASK2-Y","name":"Kids Disposable Mask","category":"ppe"},
  {"slug":"kn95-mask","sku":"TZ-MASK3","name":"KN95 Mask","category":"ppe"},
  {"slug":"level-2-medical-mask","sku":"TZ-MASK-LVL2-MED","name":"Level 2 Medical Mask","category":"ppe"},
  {"slug":"level-3-medical-mask","sku":"TZ-MASK-LVL3-MED","name":"Level 3 Medical Mask","category":"ppe"},
  {"slug":"mask-extender","sku":"TZ-SME","name":"Mask Extender","category":"ppe"},
  {"slug":"philly-special-mask","sku":"TZ-4133","name":"Philly Special Mask","category":"ppe"},
  {"slug":"polyester-mask","sku":"TZ-3PCM-AELP","name":"Polyester Mask","category":"ppe"},
  {"slug":"printed-disposable-mask","sku":"TZ-MASK2-95-DS","name":"Printed Disposable Mask","category":"ppe"},
  {"slug":"safety-glasses-goggles","sku":"TZ-SFTYGGL1","name":"Safety Glasses Goggles","category":"ppe"},
  {"slug":"safety-glasses-goggles","sku":"TZ-SFTYGL1","name":"Safety Glasses Goggles","category":"ppe"},
  {"slug":"silicone-mask-band","sku":"TZ-SMB","name":"Silicone Mask Band","category":"ppe"},
  {"slug":"smile-window-cotton-mask","sku":"TZ-4PCM-SW","name":"Smile Window Cotton Mask","category":"ppe"},
  {"slug":"touchless-infrared-thermometer","sku":"TZ-TIT","name":"Touchless Infrared Thermometer","category":"ppe"},
  {"slug":"wall-mounted-hand-sanitizer-stand","sku":"TZ-WHSS","name":"Wall Mounted Hand Sanitizer Stand","category":"ppe"},
  {"slug":"youth-cotton-mask","sku":"TZ-4PCM-Y","name":"Youth Cotton Mask","category":"ppe"},
  {"slug":"1-charge-polyester-key-tag","sku":"TZ-1C-KTP","name":"1 Charge Polyester Key Tag","category":"tech"},
  {"slug":"1charge-braided-cord","sku":"TZ-1C-BR1M","name":"1Charge Braided Cord","category":"tech"},
  {"slug":"1charge-cord","sku":"TZ-1C","name":"1Charge Cord","category":"tech"},
  {"slug":"1charge-cord-1m-long","sku":"TZ-1C-1M","name":"1Charge Cord 1m Long","category":"tech"},
  {"slug":"1charge-custom-shaped-charging-cable","sku":"TZ-1C-CC","name":"1Charge Custom Shaped Charging Cable","category":"tech"},
  {"slug":"1charge-fan","sku":"TZ-1C-F","name":"1Charge Fan","category":"tech"},
  {"slug":"1charge-key-tag","sku":"TZ-1C-KT","name":"1Charge Key Tag","category":"tech"},
  {"slug":"1charge-squid","sku":"TZ-1C-SQ","name":"1Charge Squid","category":"tech"},
  {"slug":"1charge-tassel","sku":"TZ-1C-TSL","name":"1Charge Tassel","category":"tech"},
  {"slug":"3-in-1-charge-polyester-key-tag","sku":"TZ-3C-KTP","name":"3 In 1 Charge Polyester Key Tag","category":"tech"},
  {"slug":"5000-mah-powerbank","sku":"TZPB-06","name":"5000 Mah Powerbank","category":"tech"},
  {"slug":"aluminum-case-with-epoxy-dome","sku":"SC-ALUM-ED","name":"Aluminum Case With Epoxy Dome","category":"tech"},
  {"slug":"aluminum-case-with-lapel-pin","sku":"SC-ALUM-LP","name":"Aluminum Case With Lapel Pin","category":"tech"},
  {"slug":"aluminum-circle-powerbank","sku":"TZPB-03","name":"Aluminum Circle Powerbank","category":"tech"},
  {"slug":"aluminum-smartphone-case","sku":"SC-ALUM","name":"Aluminum Smartphone Case","category":"tech"},
  {"slug":"aluminum-square-powerbank","sku":"TZPB-02","name":"Aluminum Square Powerbank","category":"tech"},
  {"slug":"bluetooth-converter","sku":"TZ-BTCV","name":"Bluetooth Converter","category":"tech"},
  {"slug":"bluetooth-converter-with-custom-shaped-earbuds","sku":"TZ-BTCV-EBCS","name":"Bluetooth Converter With Custom Shaped Earbuds","category":"tech"},
  {"slug":"bluetooth-converter-with-metal-earbuds","sku":"TZ-BTCV-MEB1","name":"Bluetooth Converter With Metal Earbuds","category":"tech"},
  {"slug":"bluetooth-earbud","sku":"TZBT-EB1","name":"Bluetooth Earbud","category":"tech"},
  {"slug":"bluetooth-selfie-stick","sku":"TZ-SS-BT","name":"Bluetooth Selfie Stick","category":"tech"},
  {"slug":"bluetooth-selfie-stick-w-powerbank-remote","sku":"TZ-SS-PBR","name":"Bluetooth Selfie Stick w/ Powerbank Remote","category":"tech"},
  {"slug":"bluetooth-selfie-stick-w-remote","sku":"TZ-SS-BTR","name":"Bluetooth Selfie Stick w/ Remote","category":"tech"},
  {"slug":"bottle-coolie-w-speaker","sku":"TZ-OS-BKS","name":"Bottle Coolie w/ Speaker","category":"tech"},
  {"slug":"cooler","sku":"TZ-CC-1","name":"Cooler","category":"tech"},
  {"slug":"cooler","sku":"TZ-CC-2","name":"Cooler","category":"tech"},
  {"slug":"copper-plated-muddler","sku":"TZ-SS-MDLR-CP","name":"Copper Plated Muddler","category":"tech"},
  {"slug":"custom-earbud-wraps","sku":"CB-W","name":"Custom Earbud Wraps","category":"tech"},
  {"slug":"custom-shaped-earbuds","sku":"EB-CS","name":"Custom Shaped Earbuds","category":"tech"},
  {"slug":"custom-silicone-molded-earbuds","sku":"EB2-3D","name":"Custom Silicone Molded Earbuds","category":"tech"},
  {"slug":"debbosed-silicone-smartphone-skin-with-colorfill","sku":"SC-CF","name":"Debbosed Silicone Smartphone Skin With Colorfill","category":"tech"},
  {"slug":"double-usb-powerbank","sku":"CH60","name":"Double USB Powerbank","category":"tech"},
  {"slug":"earbud-in-wrap-case","sku":"EB-MS","name":"Earbud In Wrap Case","category":"tech"},
  {"slug":"earbud-splitter","sku":"EB-S","name":"Earbud Splitter","category":"tech"},
  {"slug":"embossed-silicone-smartphone-skin","sku":"SC-AG","name":"Embossed Silicone Smartphone Skin","category":"tech"},
  {"slug":"epoxy-dome-earbud","sku":"EB3","name":"Epoxy Dome Earbud","category":"tech"},
  {"slug":"epoxy-dome-mini-micro-usb-charger","sku":"TZ-MMC-ED","name":"Epoxy Dome Mini Micro USB Charger","category":"tech"},
  {"slug":"foil-imprinted-smartphone-case","sku":"SC-PC-FOIL","name":"Foil Imprinted Smartphone Case","category":"tech"},
  {"slug":"hard-4cp-plastic-case-with-glossy-finish","sku":"SC-PC-4CPG","name":"Hard 4CP Plastic Case With Glossy Finish","category":"tech"},
  {"slug":"hard-plastic-case-with-cardholder","sku":"SC-PCCH","name":"Hard Plastic Case With Cardholder","category":"tech"},
  {"slug":"headphones","sku":"HP1","name":"Headphones","category":"tech"},
  {"slug":"heart-shaped-earbuds","sku":"EB-HS","name":"Heart Shaped Earbuds","category":"tech"},
  {"slug":"hoodie-earbud-pouch-eb-cs","sku":"H-EB-CS","name":"Hoodie Earbud Pouch Eb Cs","category":"tech"},
  {"slug":"hoodie-earbud-pouch-eb-vb","sku":"H-EB-VB","name":"Hoodie Earbud Pouch Eb Vb","category":"tech"},
  {"slug":"hoodie-earbud-pouch-eb2","sku":"H-EB2","name":"Hoodie Earbud Pouch Eb2","category":"tech"},
  {"slug":"lenticular-smartphone-case","sku":"SC-LENT","name":"Lenticular Smartphone Case","category":"tech"},
  {"slug":"light-up-powerbank-w-suction-cup","sku":"TZPB-LU","name":"Light Up Powerbank w/ Suction Cup","category":"tech"},
  {"slug":"magnetic-bluetooth-buds","sku":"TZ-BT-MM","name":"Magnetic Bluetooth Buds","category":"tech"},
  {"slug":"magnetic-gift-box-speaker-set","sku":"TZ-SBGS","name":"Magnetic Gift Box Speaker Set","category":"tech"},
  {"slug":"magnetic-suction-cup-phone-stand","sku":"TZ-SP-MSCPS","name":"Magnetic Suction Cup Phone Stand","category":"tech"},
  {"slug":"matte-plastic-case-4cp-imprint","sku":"SC-PC-4CPM","name":"Matte Plastic Case 4CP Imprint","category":"tech"},
  {"slug":"metal-beveled-earbuds","sku":"EB4","name":"Metal Beveled Earbuds","category":"tech"},
  {"slug":"metal-earbuds","sku":"MEB-HIFI-1","name":"Metal Earbuds","category":"tech"},
  {"slug":"on-the-go-magnetic-smartphone-powerbank","sku":"TZ-SP-MPB","name":"On The Go Magnetic Smartphone Powerbank","category":"tech"},
  {"slug":"on-the-go-magnetic-smartphone-powerbank-and-wallet","sku":"TZ-SP-MPB+W","name":"On The Go Magnetic Smartphone Powerbank And Wallet","category":"tech"},
  {"slug":"one-meter-cable-w-android-lightining-adapter-and-type-c-toggle","sku":"TZ-1C-TC-1M","name":"One Meter Cable w/ Android Lightining Adapter And Type C Toggle","category":"tech"},
  {"slug":"overear-bluetooth-buds","sku":"TZ-BT-OE","name":"Overear Bluetooth Buds","category":"tech"},
  {"slug":"plastic-case-with-dimensionally-printed-graphics","sku":"SC-D4CP","name":"Plastic Case With Dimensionally Printed Graphics","category":"tech"},
  {"slug":"portable-bluetooth-speaker","sku":"TZ-OS-PBS","name":"Portable Bluetooth Speaker","category":"tech"},
  {"slug":"portable-charger-w-custom-molded-pvc-topper","sku":"TZPB-01-T","name":"Portable Charger w/ Custom Molded PVC Topper","category":"tech"},
  {"slug":"portable-charging-powerbank","sku":"TZPB-01","name":"Portable Charging Powerbank","category":"tech"},
  {"slug":"portable-charging-powerbank","sku":"CH40","name":"Portable Charging Powerbank","category":"tech"},
  {"slug":"powerbank-speaker","sku":"TZPB-SPKR","name":"Powerbank Speaker","category":"tech"},
  {"slug":"pu-leather-phone-card-holder","sku":"LSPCH","name":"Pu Leather Phone Card Holder","category":"tech"},
  {"slug":"pu-leather-wallet-cardholder","sku":"TZ-PG-CH","name":"Pu Leather Wallet Cardholder","category":"tech"},
  {"slug":"retractable-earbuds","sku":"REB1","name":"Retractable Earbuds","category":"tech"},
  {"slug":"screen-printed-silicone-smartphone-skin","sku":"SC-SS","name":"Screen Printed Silicone Smartphone Skin","category":"tech"},
  {"slug":"selfie-stick-w-cord","sku":"TZ-SS-C","name":"Selfie Stick w/ Cord","category":"tech"},
  {"slug":"selfie-stick-w-custom-molded-grip","sku":"TZ-SS-MG","name":"Selfie Stick w/ Custom Molded Grip","category":"tech"},
  {"slug":"silicone-phone-card-holder","sku":"SPCH","name":"Silicone Phone Card Holder","category":"tech"},
  {"slug":"silicone-phone-card-holder-bottom-slot","sku":"SPCH-BS","name":"Silicone Phone Card Holder Bottom Slot","category":"tech"},
  {"slug":"silicone-phone-card-holder-bottom-slot-3d","sku":"SPCH-BS-3D","name":"Silicone Phone Card Holder Bottom Slot 3d","category":"tech"},
  {"slug":"softer-feel-fully-wrapped-4cp-imprint","sku":"SC-TPU-4CP","name":"Softer Feel Fully Wrapped 4CP Imprint","category":"tech"},
  {"slug":"standard-earbud","sku":"EB2-STANDARD","name":"Standard Earbud","category":"tech"},
  {"slug":"standard-earbud-w-mic","sku":"EB2-MIC","name":"Standard Earbud w/ Mic","category":"tech"},
  {"slug":"tablet-case","sku":"TZ-OS-TC","name":"Tablet Case","category":"tech"},
  {"slug":"textured-polyurethane-case","sku":"SC-PU","name":"Textured Polyurethane Case","category":"tech"},
  {"slug":"thin-1charge-powerbank","sku":"TZPB-FL-1C","name":"Thin 1Charge Powerbank","category":"tech"},
  {"slug":"two-tone-plastic-case","sku":"SC-PC-TT","name":"Two Tone Plastic Case","category":"tech"},
  {"slug":"two-tone-silicone-case","sku":"SC-TT","name":"Two Tone Silicone Case","category":"tech"},
  {"slug":"ul-round-powerbank","sku":"TZPB-03-UL","name":"Ul Round Powerbank","category":"tech"},
  {"slug":"ul-round-powerbank-with-led-light","sku":"TZPB-07-UL","name":"Ul Round Powerbank With LED Light","category":"tech"},
  {"slug":"ul-square-powerbank","sku":"TZPB-02-UL","name":"Ul Square Powerbank","category":"tech"},
  {"slug":"ul-square-powerbank","sku":"TZPB-01-UL","name":"Ul Square Powerbank","category":"tech"},
  {"slug":"ul-square-powerbank","sku":"TZPB-08-UL","name":"Ul Square Powerbank","category":"tech"},
  {"slug":"us-made-acrylic-smartphone-desk-stand","sku":"ACPS","name":"US Made Acrylic Smartphone Desk Stand","category":"tech"},
  {"slug":"wireless-charger-2","sku":"TZ-WC-2","name":"Wireless Charger 2","category":"tech"},
  {"slug":"wireless-charger-3-trio","sku":"TZ-WC-3","name":"Wireless Charger 3 Trio","category":"tech"},
  {"slug":"xx-l-cooler-with-bluetooth-speaker","sku":"TZ- BT - COOLER","name":"Xx L Cooler With Bluetooth Speaker","category":"tech"},
  {"slug":"1-layer-acrylic-wall-plaque","sku":"WP-1","name":"1 Layer Acrylic Wall Plaque","category":"acrylic"},
  {"slug":"4-x-6-acrylic-picture-frame-clock","sku":"US152","name":"4 X 6 Acrylic Picture Frame Clock","category":"acrylic"},
  {"slug":"4-x-6-golf-easel-frame","sku":"SHES46","name":"4 X 6 Golf Easel Frame","category":"acrylic"},
  {"slug":"4-x-6-golf-frame","sku":"SHL46","name":"4 X 6 Golf Frame","category":"acrylic"},
  {"slug":"4-x-6-golf-frame","sku":"SHSS46","name":"4 X 6 Golf Frame","category":"acrylic"},
  {"slug":"4-x-6-golf-frame","sku":"46HSF-GC","name":"4 X 6 Golf Frame","category":"acrylic"},
  {"slug":"4-x-6-golf-frame","sku":"SH2C46","name":"4 X 6 Golf Frame","category":"acrylic"},
  {"slug":"4-x-6-studded-golf-frame","sku":"SHF4C46","name":"4 X 6 Studded Golf Frame","category":"acrylic"},
  {"slug":"4-x-6-wide-golf-easel-frame","sku":"SHCL46","name":"4 X 6 Wide Golf Easel Frame","category":"acrylic"},
  {"slug":"4-x6-black-metal-picture-frame","sku":"WL46-BK","name":"4 X6 Black Metal Picture Frame","category":"acrylic"},
  {"slug":"4-x6-metal-picture-frame","sku":"WL46","name":"4 X6 Metal Picture Frame","category":"acrylic"},
  {"slug":"acrylic-book-frame-with-cirque-theme","sku":"LB- CIRQUE DU SENIORS","name":"Acrylic Book Frame With Cirque Theme","category":"acrylic"},
  {"slug":"acrylic-book-frame-with-facebook-theme","sku":"BFB-FACEBOOK","name":"Acrylic Book Frame With Facebook Theme","category":"acrylic"},
  {"slug":"acrylic-box-display","sku":"TZ-MMJ-ABD","name":"Acrylic Box Display","category":"acrylic"},
  {"slug":"acrylic-easel-bend-picture-frame","sku":"ES","name":"Acrylic Easel Bend Picture Frame","category":"acrylic"},
  {"slug":"acrylic-glove-dispensing-box","sku":"TZ-GLDISPBX","name":"Acrylic Glove Dispensing Box","category":"acrylic"},
  {"slug":"acrylic-magnetic-frames-in-leatherette-bases","sku":"BKM","name":"Acrylic Magnetic Frames In Leatherette Bases","category":"acrylic"},
  {"slug":"acrylic-pre-roll-display","sku":"TZ-MMJ-APRD","name":"Acrylic Pre Roll Display","category":"acrylic"},
  {"slug":"acrylic-statement-tent","sku":"TMS","name":"Acrylic Statement Tent","category":"acrylic"},
  {"slug":"acrylic-tray","sku":"TZ-ACRYLIC TRAY","name":"Acrylic Tray","category":"acrylic"},
  {"slug":"acrylic-tray","sku":"TZ-ATRY1208","name":"Acrylic Tray","category":"acrylic"},
  {"slug":"chalk-board-stand","sku":"TZ-OS-CBS","name":"Chalk Board Stand","category":"acrylic"},
  {"slug":"circle-easel-mirror","sku":"CEM","name":"Circle Easel Mirror","category":"acrylic"},
  {"slug":"circle-handheld-fashion-mirror","sku":"TZ-HFM-C","name":"Circle Handheld Fashion Mirror","category":"acrylic"},
  {"slug":"clear-magnetic-picture-frame","sku":"M","name":"Clear Magnetic Picture Frame","category":"acrylic"},
  {"slug":"colored-arm-w-mirror-lens","sku":"SG-SOL-CAM","name":"Colored Arm w/ Mirror Lens","category":"acrylic"},
  {"slug":"custom-shaped-wall-clock-any-size","sku":"US-CW","name":"Custom Shaped Wall Clock Any Size","category":"acrylic"},
  {"slug":"deluxe-fold-over-frame-with-leatherette-base","sku":"BVM","name":"Deluxe Fold Over Frame With Leatherette Base","category":"acrylic"},
  {"slug":"easel-coin-holder","sku":"ECH-5C","name":"Easel Coin Holder","category":"acrylic"},
  {"slug":"easel-coin-holder-w-cavity","sku":"ECH","name":"Easel Coin Holder w/ Cavity","category":"acrylic"},
  {"slug":"easel-mirror","sku":"EM","name":"Easel Mirror","category":"acrylic"},
  {"slug":"easel-mission-statement","sku":"EMS","name":"Easel Mission Statement","category":"acrylic"},
  {"slug":"easel-picture-frame-with-background","sku":"ESB","name":"Easel Picture Frame With Background","category":"acrylic"},
  {"slug":"faux-leather-table-tent","sku":"TT-FL","name":"Faux Leather Table Tent","category":"acrylic"},
  {"slug":"handheld-fashion-mirror","sku":"TZ-HFM","name":"Handheld Fashion Mirror","category":"acrylic"},
  {"slug":"injection-molded-photo-frame","sku":"TZ-OS-IMPF","name":"Injection Molded Photo Frame","category":"acrylic"},
  {"slug":"insert-tent-mission-statement","sku":"TMI","name":"Insert Tent Mission Statement","category":"acrylic"},
  {"slug":"magnetic-circle-mirror","sku":"MC","name":"Magnetic Circle Mirror","category":"acrylic"},
  {"slug":"magnetic-picture-frame-with-background","sku":"CM","name":"Magnetic Picture Frame With Background","category":"acrylic"},
  {"slug":"one-piece-table-tent","sku":"TT1","name":"One Piece Table Tent","category":"acrylic"},
  {"slug":"pms-matched-plastic-frames-and-arms","sku":"TZ-SG-WMF-PMS","name":"Pms Matched Plastic Frames And Arms","category":"acrylic"},
  {"slug":"pop-signage-easel","sku":"EMS18","name":"Pop Signage Easel","category":"acrylic"},
  {"slug":"slider-picture-frame","sku":"SF","name":"Slider Picture Frame","category":"acrylic"},
  {"slug":"table-tent-tower","sku":"TT-TWR","name":"Table Tent Tower","category":"acrylic"},
  {"slug":"thick-acrylic-magnetic-frame-in-leatherette-base","sku":"BKM-TF","name":"Thick Acrylic Magnetic Frame In Leatherette Base","category":"acrylic"},
  {"slug":"thick-magnetic-frame","sku":"TMF","name":"Thick Magnetic Frame","category":"acrylic"},
  {"slug":"union-made-acrylic-desk-clock","sku":"US101","name":"Union Made Acrylic Desk Clock","category":"acrylic"},
  {"slug":"union-made-mirror-wall-clock","sku":"US147","name":"Union Made Mirror Wall Clock","category":"acrylic"},
  {"slug":"wall-mirror","sku":"WM","name":"Wall Mirror","category":"acrylic"},
  {"slug":"1-tall-silicone-bracelet","sku":"SRB-TL","name":"1 Tall Silicone Bracelet","category":"silicone"},
  {"slug":"3-charm-bracelet","sku":"MZ-CB3","name":"3 Charm Bracelet","category":"silicone"},
  {"slug":"custom-silicone-ice-mold","sku":"TZ-OS-CSIM","name":"Custom Silicone Ice Mold","category":"silicone"},
  {"slug":"debossed-silicone-awarenes-bracelet","sku":"SRB-DEB","name":"Debossed Silicone Awarenes Bracelet","category":"silicone"},
  {"slug":"glow-bracelet","sku":"TZ-BR-GLOW","name":"Glow Bracelet","category":"silicone"},
  {"slug":"lcd-silicone-watch","sku":"SL-LCD","name":"LCD Silicone Watch","category":"silicone"},
  {"slug":"leather-cuff-bracelet","sku":"TZ-LCUFF-B","name":"Leather Cuff Bracelet","category":"silicone"},
  {"slug":"leather-hook-bracelet","sku":"TZ-LHB","name":"Leather Hook Bracelet","category":"silicone"},
  {"slug":"led-bracelet","sku":"TZ-BR-LED","name":"LED Bracelet","category":"silicone"},
  {"slug":"mini-silicone-slap-bracelet","sku":"TZ-MSLB","name":"Mini Silicone Slap Bracelet","category":"silicone"},
  {"slug":"screenprinted-silicone-awareness-bracelet","sku":"SRB-SCR","name":"Screenprinted Silicone Awareness Bracelet","category":"silicone"},
  {"slug":"sequin-slap-bracelet","sku":"SLB-SQ","name":"Sequin Slap Bracelet","category":"silicone"},
  {"slug":"silicone-and-glass-jars","sku":"SILICONE AND GLASS JARS","name":"Silicone And Glass Jars","category":"silicone"},
  {"slug":"silicone-awareness-bracelet","sku":"SRB-5MM","name":"Silicone Awareness Bracelet","category":"silicone"},
  {"slug":"silicone-awareness-bracelet-with-charm","sku":"SRB-5MM-CH","name":"Silicone Awareness Bracelet With Charm","category":"silicone"},
  {"slug":"silicone-bracelet-keytag","sku":"SRB-5MM-KR","name":"Silicone Bracelet Keytag","category":"silicone"},
  {"slug":"silicone-edibles-tray","sku":"TZ-MMJ-SET","name":"Silicone Edibles Tray","category":"silicone"},
  {"slug":"silicone-keytag","sku":"SRB-KT","name":"Silicone Keytag","category":"silicone"},
  {"slug":"silicone-kick-stand","sku":"SKS","name":"Silicone Kick Stand","category":"silicone"},
  {"slug":"silicone-lcd-watch-wristband","sku":"SRB-LCD","name":"Silicone LCD Watch Wristband","category":"silicone"},
  {"slug":"silicone-shot-glass","sku":"TZ-OS-SSG","name":"Silicone Shot Glass","category":"silicone"},
  {"slug":"silicone-slap-bracelet","sku":"SLB","name":"Silicone Slap Bracelet","category":"silicone"},
  {"slug":"silicone-straw","sku":"TZ-SIL-S","name":"Silicone Straw","category":"silicone"},
  {"slug":"silicone-wristband-w-racing-stripe","sku":"SRB-A-RS","name":"Silicone Wristband w/ Racing Stripe","category":"silicone"},
  {"slug":"slap-bracelet-w-colorfill","sku":"SLB-CF","name":"Slap Bracelet w/ Colorfill","category":"silicone"},
  {"slug":"uv-sensing-silicone-awareness-bracelet","sku":"SRB-UV","name":"UV Sensing Silicone Awareness Bracelet","category":"silicone"},
  {"slug":"wood-bead-bracelet","sku":"TZ-WBB","name":"Wood Bead Bracelet","category":"silicone"},
  {"slug":"1-2-lanyard","sku":"12LYD-SCR","name":"1 2 Lanyard","category":"lanyards"},
  {"slug":"1-2-lanyard","sku":"12LYD-DS","name":"1 2 Lanyard","category":"lanyards"},
  {"slug":"1-3-4-elastic-hair-tie-on-card","sku":"34EHT-1C","name":"1 3 4 Elastic Hair Tie On Card","category":"lanyards"},
  {"slug":"1-elastic-headband","sku":"1EHB","name":"1 Elastic Headband","category":"lanyards"},
  {"slug":"1-lanyard","sku":"1LYD-DS","name":"1 Lanyard","category":"lanyards"},
  {"slug":"2-3-4-elastic-hair-ties-on-card","sku":"34EHT-2C","name":"2 3 4 Elastic Hair Ties On Card","category":"lanyards"},
  {"slug":"3-3-4-elastic-hair-ties-on-card","sku":"34EHT-3C","name":"3 3 4 Elastic Hair Ties On Card","category":"lanyards"},
  {"slug":"3-4-elastic-hair-tie","sku":"34EHT","name":"3 4 Elastic Hair Tie","category":"lanyards"},
  {"slug":"3-4-lanyard","sku":"34LYD-SCR","name":"3 4 Lanyard","category":"lanyards"},
  {"slug":"3-4-lanyard","sku":"34LYD-DS","name":"3 4 Lanyard","category":"lanyards"},
  {"slug":"3-8-lanyard","sku":"38LYD-DS","name":"3 8 Lanyard","category":"lanyards"},
  {"slug":"3-8-lanyard","sku":"38LYD-SCR","name":"3 8 Lanyard","category":"lanyards"},
  {"slug":"badges","sku":"CUSTOM LANYARD BADGE","name":"Badges","category":"lanyards"},
  {"slug":"custom-lanyard","sku":"TZ-LYD-CLEAR POUCH","name":"Custom Lanyard","category":"lanyards"},
  {"slug":"flat-style-shoelaces-with-1-color-imprint","sku":"TZ-SL1C","name":"Flat Style Shoelaces With 1 Color Imprint","category":"lanyards"},
  {"slug":"flat-style-shoelaces-with-2-color-imprint","sku":"TZ-SL2C","name":"Flat Style Shoelaces With 2 Color Imprint","category":"lanyards"},
  {"slug":"flat-style-shoelaces-with-dye-sublimation-imprint","sku":"TZ-SLDS","name":"Flat Style Shoelaces With Dye Sublimation Imprint","category":"lanyards"},
  {"slug":"garter","sku":"TZ-GT","name":"Garter","category":"lanyards"},
  {"slug":"tube-style-shoelaces-with-1-color-imprint","sku":"TZ-SLT1C","name":"Tube Style Shoelaces With 1 Color Imprint","category":"lanyards"},
  {"slug":"tube-style-shoelaces-with-2-color-imprint","sku":"TZ-SLT2C","name":"Tube Style Shoelaces With 2 Color Imprint","category":"lanyards"},
  {"slug":"tube-style-shoelaces-with-dye-sublimation-imprint","sku":"TZ-SLTDS","name":"Tube Style Shoelaces With Dye Sublimation Imprint","category":"lanyards"},
  {"slug":"1-color-standard-sunglasses","sku":"SG-WF","name":"1 Color Standard Sunglasses","category":"sunglasses"},
  {"slug":"2-tone-standard-sunglasses","sku":"SG-WFTT","name":"2 Tone Standard Sunglasses","category":"sunglasses"},
  {"slug":"3d-glasses","sku":"SG-WF-3D","name":"3d Glasses","category":"sunglasses"},
  {"slug":"color-block-standard-sunglasses","sku":"SG-WFCB","name":"Color Block Standard Sunglasses","category":"sunglasses"},
  {"slug":"foldable-sunglasses","sku":"SG-FS","name":"Foldable Sunglasses","category":"sunglasses"},
  {"slug":"half-half-standard-sunglasses","sku":"SG-WFHH","name":"Half Half Standard Sunglasses","category":"sunglasses"},
  {"slug":"kids-standard-sunglasses","sku":"SG-KWF","name":"Kids Standard Sunglasses","category":"sunglasses"},
  {"slug":"matte-sunglasses-with-rubber-finish","sku":"SG-RWF","name":"Matte Sunglasses With Rubber Finish","category":"sunglasses"},
  {"slug":"metal-aviator-style-sunglasses","sku":"SG-MAV","name":"Metal Aviator Style Sunglasses","category":"sunglasses"},
  {"slug":"metallic-sunglasses","sku":"SG-WFM","name":"Metallic Sunglasses","category":"sunglasses"},
  {"slug":"new-wood-arm-sunglasses","sku":"SG-WA-WF","name":"New Wood Arm Sunglasses","category":"sunglasses"},
  {"slug":"plastic-aviator-style-sunglasses","sku":"SG-AV","name":"Plastic Aviator Style Sunglasses","category":"sunglasses"},
  {"slug":"plastic-bezel-metal-aviator","sku":"SG-PBAV","name":"Plastic Bezel Metal Aviator","category":"sunglasses"},
  {"slug":"polycarbonate-tortoiseshell-sunglasses","sku":"TZ-SG-WMF-TS","name":"Polycarbonate Tortoiseshell Sunglasses","category":"sunglasses"},
  {"slug":"tortoise-sunglasses","sku":"SG-WF-TS","name":"Tortoise Sunglasses","category":"sunglasses"},
  {"slug":"womens-sunglasses","sku":"SG-JAKEO","name":"Womens Sunglasses","category":"sunglasses"},
  {"slug":"wood-arm-aviator","sku":"SG-WA-AV-MA","name":"Wood Arm Aviator","category":"sunglasses"},
  {"slug":"wood-arm-aviator","sku":"SG-WA-AV","name":"Wood Arm Aviator","category":"sunglasses"},
  {"slug":"wood-grain-sunglasses","sku":"SG-W53","name":"Wood Grain Sunglasses","category":"sunglasses"},
  {"slug":"wood-grain-sunglasses","sku":"SG-W52","name":"Wood Grain Sunglasses","category":"sunglasses"},
  {"slug":"wood-grain-sunglasses","sku":"SG-W54","name":"Wood Grain Sunglasses","category":"sunglasses"},
  {"slug":"wood-grain-sunglasses","sku":"TZ-SG-WMF-NG","name":"Wood Grain Sunglasses","category":"sunglasses"},
  {"slug":"youth-sunglasses","sku":"SG-KIDS","name":"Youth Sunglasses","category":"sunglasses"},
  {"slug":"4-screw-wall-opener","sku":"4S-WO","name":"4 Screw Wall Opener","category":"drinkware"},
  {"slug":"acacia-wine-dip-gold","sku":"TZ-WDC-GOLD","name":"Acacia Wine Dip Gold","category":"drinkware"},
  {"slug":"acacia-wine-dip-silver","sku":"TZ-WDC-SILVER","name":"Acacia Wine Dip Silver","category":"drinkware"},
  {"slug":"bartender-kit","sku":"TZ-OS-BK","name":"Bartender Kit","category":"drinkware"},
  {"slug":"beer-tower","sku":"TZ-OS-BT","name":"Beer Tower","category":"drinkware"},
  {"slug":"beer-tower","sku":"TZ-BEER-TWR","name":"Beer Tower","category":"drinkware"},
  {"slug":"black-rail-mat","sku":"TZ-RAIL-MAT-BLK","name":"Black Rail Mat","category":"drinkware"},
  {"slug":"bottle-glorifier-strip","sku":"TZ-BGS","name":"Bottle Glorifier Strip","category":"drinkware"},
  {"slug":"ceramic-mug","sku":"TZ-OS-CD-M","name":"Ceramic Mug","category":"drinkware"},
  {"slug":"circle-epoxy-dome-bottle-opener-w-key-ring-double-sided","sku":"MZ-STBO-1R","name":"Circle Epoxy Dome Bottle Opener w/ Key Ring Double Sided","category":"drinkware"},
  {"slug":"collapsible-stainless-steel-straw-kit","sku":"TZ-CSTL-SK","name":"Collapsible Stainless Steel Straw Kit","category":"drinkware"},
  {"slug":"colored-rail-mat","sku":"TZ-RAIL MAT-CLR","name":"Colored Rail Mat","category":"drinkware"},
  {"slug":"condiment-tray","sku":"TZ-OS-CT","name":"Condiment Tray","category":"drinkware"},
  {"slug":"copper-mug","sku":"TZ-OS-CM","name":"Copper Mug","category":"drinkware"},
  {"slug":"corkscrew-wine-opener-with-foil-cutter","sku":"CORKSCREW WINE OPENER WITH FOIL CUTTER","name":"Corkscrew Wine Opener With Foil Cutter","category":"drinkware"},
  {"slug":"custom-coolie","sku":"TZ-COOLIE","name":"Custom Coolie","category":"drinkware"},
  {"slug":"deluxe-cloisonne-opener-ornament","sku":"TZ-DCLO-ORN","name":"Deluxe Cloisonne Opener Ornament","category":"drinkware"},
  {"slug":"disposable-shot-glass","sku":"TZ-SG-DISP","name":"Disposable Shot Glass","category":"drinkware"},
  {"slug":"disposable-shot-glass-with-hook","sku":"TZ-SG-DISP-H","name":"Disposable Shot Glass With Hook","category":"drinkware"},
  {"slug":"double-jigger","sku":"DOUBLE JIGGER","name":"Double Jigger","category":"drinkware"},
  {"slug":"double-wall-shot-glass","sku":"TZ-SG-DBW","name":"Double Wall Shot Glass","category":"drinkware"},
  {"slug":"drink-stirrers","sku":"TZ-OS-DS","name":"Drink Stirrers","category":"drinkware"},
  {"slug":"felt-wine-gift-bag","sku":"TZ-OS-FWGB","name":"Felt Wine Gift Bag","category":"drinkware"},
  {"slug":"full-epoxy-keychain-opener","sku":"MZ-STBO-ED","name":"Full Epoxy Keychain Opener","category":"drinkware"},
  {"slug":"ice-ball-mold","sku":"TZ-OS-IBM","name":"Ice Ball Mold","category":"drinkware"},
  {"slug":"ice-mold-w-cocktail-stirrers","sku":"TZ-OS-IMCS","name":"Ice Mold w/ Cocktail Stirrers","category":"drinkware"},
  {"slug":"jersey-coolie","sku":"TZ-JZ-K2","name":"Jersey Coolie","category":"drinkware"},
  {"slug":"led-bottle-glorifier","sku":"TZ-BG-LED","name":"LED Bottle Glorifier","category":"drinkware"},
  {"slug":"led-bottle-light","sku":"PL-750 MILG","name":"LED Bottle Light","category":"drinkware"},
  {"slug":"logo-light-opener","sku":"LGL-OPEN","name":"Logo Light Opener","category":"drinkware"},
  {"slug":"napkin-caddy","sku":"TZ-OS-NC","name":"Napkin Caddy","category":"drinkware"},
  {"slug":"neoprene-bottle-jersey","sku":"TZ-NBJ","name":"Neoprene Bottle Jersey","category":"drinkware"},
  {"slug":"neoprene-bottle-sleeve","sku":"TZ-NBS","name":"Neoprene Bottle Sleeve","category":"drinkware"},
  {"slug":"paper-straw","sku":"TZ-PP-S","name":"Paper Straw","category":"drinkware"},
  {"slug":"plastic-drink-ball","sku":"TZ-OS-DB","name":"Plastic Drink Ball","category":"drinkware"},
  {"slug":"plastic-shot-glass","sku":"TZ-SG-P","name":"Plastic Shot Glass","category":"drinkware"},
  {"slug":"rail-bar-mat","sku":"PVC-BMR","name":"Rail Bar Mat","category":"drinkware"},
  {"slug":"shot-glass","sku":"TZ-SG","name":"Shot Glass","category":"drinkware"},
  {"slug":"six-led-bottle-light","sku":"TZ-OS-6LED","name":"Six LED Bottle Light","category":"drinkware"},
  {"slug":"skull-cup","sku":"TZ-SKLCP","name":"Skull Cup","category":"drinkware"},
  {"slug":"soapstone-whiskey-stones","sku":"TZ-IC-SST","name":"Soapstone Whiskey Stones","category":"drinkware"},
  {"slug":"solo-cup-shot-glass","sku":"TZ-SG-SOLO","name":"Solo Cup Shot Glass","category":"drinkware"},
  {"slug":"spoon-with-muddler","sku":"TZ-SPMD","name":"Spoon With Muddler","category":"drinkware"},
  {"slug":"stainless-steel-shot-glass","sku":"TZ-SG-STL","name":"Stainless Steel Shot Glass","category":"drinkware"},
  {"slug":"stainless-steel-whiskey-stones","sku":"TZ-IC-STNLS","name":"Stainless Steel Whiskey Stones","category":"drinkware"},
  {"slug":"stainless-straw","sku":"TZ-STL-S","name":"Stainless Straw","category":"drinkware"},
  {"slug":"strainer","sku":"STRAINER","name":"Strainer","category":"drinkware"},
  {"slug":"strainers","sku":"TZ-CSTI","name":"Strainers","category":"drinkware"},
  {"slug":"straw-hat","sku":"CUSTOM-STRAW HAT","name":"Straw Hat","category":"drinkware"},
  {"slug":"talking-soccer-ball-opener","sku":"TZ-OS-TSBO","name":"Talking Soccer Ball Opener","category":"drinkware"},
  {"slug":"tall-shot-glass","sku":"TZ-SG-T","name":"Tall Shot Glass","category":"drinkware"},
  {"slug":"three-piece-shaker","sku":"TZ-3PC-SHAKER","name":"Three Piece Shaker","category":"drinkware"},
  {"slug":"tz-tasting-kit","sku":"TZ- TASTING KIT","name":"TZ Tasting Kit","category":"drinkware"},
  {"slug":"vinyl-dipped-speed-opener","sku":"TZ-VSO1","name":"Vinyl Dipped Speed Opener","category":"drinkware"},
  {"slug":"wall-mounted-opener-w-2-screws","sku":"TZ-WMBO-2S","name":"Wall Mounted Opener w/ 2 Screws","category":"drinkware"},
  {"slug":"wine-charm-set","sku":"MZ-WC-SET","name":"Wine Charm Set","category":"drinkware"},
  {"slug":"wooden-muddler","sku":"TZ-MDLR-WD","name":"Wooden Muddler","category":"drinkware"},
  {"slug":"aluminum-luggage-tag","sku":"MZLT-10","name":"Aluminum Luggage Tag","category":"apparel"},
  {"slug":"backpack","sku":"TZ-OS-B","name":"Backpack","category":"apparel"},
  {"slug":"bucket-hats","sku":"TZ-BUCKETHAT","name":"Bucket Hats","category":"apparel"},
  {"slug":"canvas-messenger-bag","sku":"CUSTOM","name":"Canvas Messenger Bag","category":"apparel"},
  {"slug":"cosmetic-case","sku":"TZ-COS1","name":"Cosmetic Case","category":"apparel"},
  {"slug":"custom-bags","sku":"CUSTOM BAGS","name":"Custom Bags","category":"apparel"},
  {"slug":"custom-doctor-bag","sku":"TZ-DRBAG","name":"Custom Doctor Bag","category":"apparel"},
  {"slug":"custom-hats","sku":"TZ-OS-CH","name":"Custom Hats","category":"apparel"},
  {"slug":"custom-knife","sku":"KNIFE","name":"Custom Knife","category":"apparel"},
  {"slug":"custom-luggage","sku":"TZ-CSLG","name":"Custom Luggage","category":"apparel"},
  {"slug":"customizable-scarf","sku":"TZ-OS-CF","name":"Customizable Scarf","category":"apparel"},
  {"slug":"girls-hbo-fringe-bag","sku":"TZ-FRINGE BAG","name":"Girls HBO Fringe Bag","category":"apparel"},
  {"slug":"hat-clip-with-ball-marker","sku":"MZ-BM-1","name":"Hat Clip With Ball Marker","category":"apparel"},
  {"slug":"hat-clip-with-ball-marker","sku":"MZ-BM-3","name":"Hat Clip With Ball Marker","category":"apparel"},
  {"slug":"luggage-strap","sku":"TZ-LGSP","name":"Luggage Strap","category":"apparel"},
  {"slug":"neoprene-carry-sleeve","sku":"TZ-NCS","name":"Neoprene Carry Sleeve","category":"apparel"},
  {"slug":"neoprene-luggage-grip","sku":"TZ-NLG","name":"Neoprene Luggage Grip","category":"apparel"},
  {"slug":"new-mother-hospital-bag","sku":"TZ-OS-NMHB","name":"New Mother Hospital Bag","category":"apparel"},
  {"slug":"non-woven-cap","sku":"TZ-NWC","name":"Non Woven Cap","category":"apparel"},
  {"slug":"paper-gift-bags","sku":"TZ-OS-GB","name":"Paper Gift Bags","category":"apparel"},
  {"slug":"pillow","sku":"TZ-OS-P","name":"Pillow","category":"apparel"},
  {"slug":"plastic-luggage-tag","sku":"TZ-PLLT","name":"Plastic Luggage Tag","category":"apparel"},
  {"slug":"tall-gift-bag","sku":"CP-GB-T1","name":"Tall Gift Bag","category":"apparel"},
  {"slug":"trucker-hat-with-woven-patch","sku":"TRUCKER HAT","name":"Trucker Hat With Woven Patch","category":"apparel"},
  {"slug":"umbrella","sku":"TZ-OS-U","name":"Umbrella","category":"apparel"},
  {"slug":"vegan-leather-luggage-tag-with-air-tag-holder","sku":"TZ-LT-AT","name":"Vegan Leather Luggage Tag With Air Tag Holder","category":"apparel"},
  {"slug":"wide-gift-bag","sku":"CP-GB-W1","name":"Wide Gift Bag","category":"apparel"},
  {"slug":"youth-airplane-backpack","sku":"TZ-OS-YAB","name":"Youth Airplane Backpack","category":"apparel"},
  {"slug":"5-keychain-w-android-lightening-adapter-and-type-c-toggle","sku":"TZ-TCKT1","name":"5 Keychain w/ Android Lightening Adapter And Type C Toggle","category":"emblems"},
  {"slug":"8-keychain-w-android-lightining-adapter-and-type-c-toggle","sku":"TZ-TCKT2","name":"8 Keychain w/ Android Lightining Adapter And Type C Toggle","category":"emblems"},
  {"slug":"award-medal","sku":"MZ-AW","name":"Award Medal","category":"emblems"},
  {"slug":"bull-bear-keytag","sku":"BNB-SR","name":"Bull Bear Keytag","category":"emblems"},
  {"slug":"charm-key-tag","sku":"CHRM","name":"Charm Key Tag","category":"emblems"},
  {"slug":"cloisonne-lapel-pin","sku":"CLOP","name":"Cloisonne Lapel Pin","category":"emblems"},
  {"slug":"coin","sku":"MZ-CC","name":"Coin","category":"emblems"},
  {"slug":"connector-key-tag","sku":"MZ-CNMLS","name":"Connector Key Tag","category":"emblems"},
  {"slug":"connector-key-tag","sku":"MZ-CNMC","name":"Connector Key Tag","category":"emblems"},
  {"slug":"custom-die-struck-key-tag","sku":"DSKT","name":"Custom Die Struck Key Tag","category":"emblems"},
  {"slug":"custom-keytag","sku":"TZ-KT-CUSTOM","name":"Custom Keytag","category":"emblems"},
  {"slug":"deluxe-cloisonne-lapel-pin","sku":"DCLOP","name":"Deluxe Cloisonne Lapel Pin","category":"emblems"},
  {"slug":"die-struck-2-tone-lapel-pin","sku":"DS2T","name":"Die Struck 2 Tone Lapel Pin","category":"emblems"},
  {"slug":"eiffel-tower-keytag","sku":"EIFFEL-SR","name":"Eiffel Tower Keytag","category":"emblems"},
  {"slug":"logo-light-with-keychain","sku":"LGL-1","name":"Logo Light With Keychain","category":"emblems"},
  {"slug":"photo-dome-lapel-pin-aluminum","sku":"PDLP-AL","name":"Photo Dome Lapel Pin Aluminum","category":"emblems"},
  {"slug":"rounded-rectangle-key-tag","sku":"MZKT-01","name":"Rounded Rectangle Key Tag","category":"emblems"},
  {"slug":"screen-dome-lapel-pin","sku":"SDLP","name":"Screen Dome Lapel Pin","category":"emblems"},
  {"slug":"soft-enamel-lapel-pin","sku":"SE","name":"Soft Enamel Lapel Pin","category":"emblems"},
  {"slug":"stamped-aluminum-dog-tag","sku":"MZD-SA","name":"Stamped Aluminum Dog Tag","category":"emblems"},
  {"slug":"star-keytag","sku":"STAR-SR","name":"Star Keytag","category":"emblems"},
  {"slug":"thin-stamped-aluminum-dog-tag","sku":"MZD-V","name":"Thin Stamped Aluminum Dog Tag","category":"emblems"},
  {"slug":"uv-printed-lapel-pins","sku":"TZ-DCLO-UV","name":"UV Printed Lapel Pins","category":"emblems"},
  {"slug":"4c-vegan-leather-wallet","sku":"SPCH-PU-4C","name":"4c Vegan Leather Wallet","category":"office"},
  {"slug":"customizable-playing-card","sku":"TZ-OS-CPC","name":"Customizable Playing Card","category":"office"},
  {"slug":"double-sided-bilingual-calendar","sku":"TZ-OS-DBC","name":"Double Sided Bilingual Calendar","category":"office"},
  {"slug":"journal","sku":"TZ-JOURNAL","name":"Journal","category":"office"},
  {"slug":"leather-wallet-with-money-clip","sku":"MZ-MC-W","name":"Leather Wallet With Money Clip","category":"office"},
  {"slug":"logo-light-pen","sku":"LGL-2","name":"Logo Light Pen","category":"office"},
  {"slug":"aluminum-one-hitter","sku":"TZ-MMJ-AL1H","name":"Aluminum One Hitter","category":"cannabis"},
  {"slug":"cart-box-with-window","sku":"TZ-MMJ-CBW","name":"Cart Box With Window","category":"cannabis"},
  {"slug":"concentrate-compacts","sku":"TZ-MMJ-CC","name":"Concentrate Compacts","category":"cannabis"},
  {"slug":"concentrate-containers","sku":"SCJ-3","name":"Concentrate Containers","category":"cannabis"},
  {"slug":"custom-packaging-for-disposable-batteries","sku":"TZ-MMJ-B","name":"Custom Packaging For Disposable Batteries","category":"cannabis"},
  {"slug":"custom-slide-box-for-disposable-batteries","sku":"TZ-MMJ-BS","name":"Custom Slide Box For Disposable Batteries","category":"cannabis"},
  {"slug":"custom-slide-box-for-oil-cartridge","sku":"TZ-MMJ-OCS","name":"Custom Slide Box For Oil Cartridge","category":"cannabis"},
  {"slug":"dab-mat","sku":"TZ-MMJ-DM","name":"Dab Mat","category":"cannabis"},
  {"slug":"deluxe-magnetic-box","sku":"TZ-MMJ-DMB","name":"Deluxe Magnetic Box","category":"cannabis"},
  {"slug":"dog-walker-tin","sku":"TZ-MMJ-DWT","name":"Dog Walker Tin","category":"cannabis"},
  {"slug":"exit-bags","sku":"TZ-MMJ-EB","name":"Exit Bags","category":"cannabis"},
  {"slug":"glass-chillum","sku":"TZ-MMJ-GC","name":"Glass Chillum","category":"cannabis"},
  {"slug":"grinders","sku":"GRINDERS","name":"Grinders","category":"cannabis"},
  {"slug":"joint-roller","sku":"TZ-MMJ-JR","name":"Joint Roller","category":"cannabis"},
  {"slug":"lock-load","sku":"TZ-MMJ-LNL","name":"Lock Load","category":"cannabis"},
  {"slug":"oil-cartridge","sku":"MMJ","name":"Oil Cartridge","category":"cannabis"},
  {"slug":"one-piece-gift-box","sku":"TZ-MMJ-1PGB","name":"One Piece Gift Box","category":"cannabis"},
  {"slug":"plastic-grinder","sku":"TZ-PG2","name":"Plastic Grinder","category":"cannabis"},
  {"slug":"plastic-grinder-with-storage","sku":"TZ-MMJ-PG","name":"Plastic Grinder With Storage","category":"cannabis"},
  {"slug":"rolling-papers","sku":"TZ-MMJ-RP","name":"Rolling Papers","category":"cannabis"},
  {"slug":"rolling-tray","sku":"TZ-7PP-RT","name":"Rolling Tray","category":"cannabis"},
  {"slug":"two-piece-slide-box","sku":"TZ-MMJ-2PSB1","name":"Two Piece Slide Box","category":"cannabis"},
  {"slug":"two-piece-slide-box","sku":"TZ-MMJ-2PSB3","name":"Two Piece Slide Box","category":"cannabis"},
  {"slug":"two-piece-slide-box","sku":"TZ-MMJ-2PSB2","name":"Two Piece Slide Box","category":"cannabis"},
  {"slug":"two-piece-thicker-box","sku":"TZ-MMJ-2PTB","name":"Two Piece Thicker Box","category":"cannabis"},
  {"slug":"book-style-box","sku":"TZ-CP-BK","name":"Book Style Box","category":"packaging"},
  {"slug":"box-with-magnetic-lid","sku":"CP-MB-1","name":"Box With Magnetic Lid","category":"packaging"},
  {"slug":"box-with-slide-out-tray","sku":"TZ-CP-BXTR","name":"Box With Slide Out Tray","category":"packaging"},
  {"slug":"horizontal-slip-box","sku":"TZ-CP-HSB","name":"Horizontal Slip Box","category":"packaging"},
  {"slug":"magnetic-gift-box","sku":"TZ-MGB","name":"Magnetic Gift Box","category":"packaging"},
  {"slug":"product-box-with-window","sku":"CP-BXW-1","name":"Product Box With Window","category":"packaging"},
  {"slug":"vertical-slip-box","sku":"TZ-CP-VSB","name":"Vertical Slip Box","category":"packaging"},
  {"slug":"3-in-1-lens-kit-in-custom-box","sku":"TZ-LK-CP","name":"3 In 1 Lens Kit In Custom Box","category":"other"},
  {"slug":"90-2-piece-table-shield","sku":"TZ-V2X","name":"90 2 Piece Table Shield","category":"other"},
  {"slug":"adjustable-battery","sku":"TZ-7PP-B9","name":"Adjustable Battery","category":"other"},
  {"slug":"air-vent-dash-phone-holder","sku":"TZ-AVD-PH","name":"Air Vent Dash Phone Holder","category":"other"},
  {"slug":"air-vent-phone-holder","sku":"TZ-AVPH","name":"Air Vent Phone Holder","category":"other"},
  {"slug":"asian-lantern","sku":"TZ-OS-AL","name":"Asian Lantern","category":"other"},
  {"slug":"b-4-rechargeable-battery-zeus","sku":"TZ-7PP-B4","name":"B 4 Rechargeable Battery Zeus","category":"other"},
  {"slug":"b1-rechargeable-battery","sku":"TZ-7PP-B1","name":"B1 Rechargeable Battery","category":"other"},
  {"slug":"b2-rechargeable-battery","sku":"TZ-7PP-B2","name":"B2 Rechargeable Battery","category":"other"},
  {"slug":"b3-rechargeable-battery","sku":"TZ-7PP-B3","name":"B3 Rechargeable Battery","category":"other"},
  {"slug":"b6-rechargeable-stick-battery","sku":"TZ-7PP-B6","name":"B6 Rechargeable Stick Battery","category":"other"},
  {"slug":"bamboo-utensil-kit","sku":"TZ-UK-B","name":"Bamboo Utensil Kit","category":"other"},
  {"slug":"caxirola","sku":"TZ-OS-CAXIROLA","name":"Caxirola","category":"other"},
  {"slug":"ceramic-bowl","sku":"TZ-OS-CD-B","name":"Ceramic Bowl","category":"other"},
  {"slug":"ceramic-dinner-plate","sku":"TZ-OS-CD-D","name":"Ceramic Dinner Plate","category":"other"},
  {"slug":"ceramic-salad-plate","sku":"TZ-OS-CD-S","name":"Ceramic Salad Plate","category":"other"},
  {"slug":"coaster","sku":"COASTER-F","name":"Coaster","category":"other"},
  {"slug":"container","sku":"CONTAINER","name":"Container","category":"other"},
  {"slug":"cookie-cutter","sku":"TZ-COOKIE","name":"Cookie Cutter","category":"other"},
  {"slug":"counter-viral-standing-shield","sku":"TZ-VS3P","name":"Counter Viral Standing Shield","category":"other"},
  {"slug":"custom-ceramic-dinnerware-set","sku":"TZ-OS-CD-SET","name":"Custom Ceramic Dinnerware Set","category":"other"},
  {"slug":"custom-container-and-cartridge-boxes","sku":"CUSTOM CONTAINER AND CARTRIDGE BOXES","name":"Custom Container And Cartridge Boxes","category":"other"},
  {"slug":"custom-inflatable-heart","sku":"TZ-C-HEART","name":"Custom Inflatable Heart","category":"other"},
  {"slug":"custom-shaped-replica-clock","sku":"GB400","name":"Custom Shaped Replica Clock","category":"other"},
  {"slug":"custom-soccer-ball","sku":"TZ-PU-SB","name":"Custom Soccer Ball","category":"other"},
  {"slug":"custom-ugly-sweater","sku":"TZ-UGLYSW","name":"Custom Ugly Sweater","category":"other"},
  {"slug":"desktop-shields","sku":"TZ-UB","name":"Desktop Shields","category":"other"},
  {"slug":"divot-tool","sku":"TZ-BN-DT","name":"Divot Tool","category":"other"},
  {"slug":"easy-stand","sku":"TZ-EZ-STD","name":"Easy Stand","category":"other"},
  {"slug":"freezer-rack-dispenser","sku":"TZ-OS-FRD","name":"Freezer Rack Dispenser","category":"other"},
  {"slug":"glass-jars","sku":"GSJ-S","name":"Glass Jars","category":"other"},
  {"slug":"glow-necklace","sku":"TZ-NK-GLOW","name":"Glow Necklace","category":"other"},
  {"slug":"hinged-u-shield","sku":"TZ-V3U","name":"Hinged U Shield","category":"other"},
  {"slug":"light-up-charging-squid","sku":"TZ-LU-SQ","name":"Light Up Charging Squid","category":"other"},
  {"slug":"magnetic-blue-tooth-custom-shaped-ear-buds","sku":"TZ-BT-MM-CS","name":"Magnetic Blue Tooth Custom Shaped Ear Buds","category":"other"},
  {"slug":"magnetic-close-boxes","sku":"MAGNETIC CLOSE BOXES","name":"Magnetic Close Boxes","category":"other"},
  {"slug":"magnifier","sku":"TZ-MGNFR","name":"Magnifier","category":"other"},
  {"slug":"nano-b7-rechargeable-battery","sku":"TZ-7PP-B7-NANO","name":"Nano B7 Rechargeable Battery","category":"other"},
  {"slug":"neoprene-10-quot-x-12-quot-pouch","sku":"TZ-NP-LG","name":"Neoprene 10 Quot X 12 Quot Pouch","category":"other"},
  {"slug":"neoprene-5-quot-x-7-quot-pouch","sku":"TZ-NP-SM","name":"Neoprene 5 Quot X 7 Quot Pouch","category":"other"},
  {"slug":"neoprene-7-quot-x-9-quot-pouch","sku":"TZ-NP-MD","name":"Neoprene 7 Quot X 9 Quot Pouch","category":"other"},
  {"slug":"non-woven-boot-covers","sku":"TZ-NWBC","name":"Non Woven Boot Covers","category":"other"},
  {"slug":"one-size-spray-protection-shield","sku":"TZ-FS2P-913","name":"One Size Spray Protection Shield","category":"other"},
  {"slug":"ornament","sku":"TZ-ORMT","name":"Ornament","category":"other"},
  {"slug":"ping-pong-ball","sku":"TZ-OS-PPB","name":"Ping Pong Ball","category":"other"},
  {"slug":"plush-toy","sku":"TZ-OS-PT","name":"Plush Toy","category":"other"},
  {"slug":"pvc-coaster","sku":"TZ-BN-PVC-CSTR","name":"PVC Coaster","category":"other"},
  {"slug":"resin-christmas-ornament","sku":"TZ-OS-RCO","name":"Resin Christmas Ornament","category":"other"},
  {"slug":"restaurant-kit","sku":"TZ-OS-RK","name":"Restaurant Kit","category":"other"},
  {"slug":"seat-blocker","sku":"TZ-SB1, SEAT BLOCKER","name":"Seat Blocker","category":"other"},
  {"slug":"seat-blocker","sku":"TZ-SB2","name":"Seat Blocker","category":"other"},
  {"slug":"seat-blocker","sku":"TZ-SB3","name":"Seat Blocker","category":"other"},
  {"slug":"seat-blocker","sku":"TZ-BBSB","name":"Seat Blocker","category":"other"},
  {"slug":"server-mat","sku":"TZ-SVRMT","name":"Server Mat","category":"other"},
  {"slug":"slide-box-with-paper-insert","sku":"TZ-SB-PPI","name":"Slide Box With Paper Insert","category":"other"},
  {"slug":"slide-boxes","sku":"SLIDE BOXES","name":"Slide Boxes","category":"other"},
  {"slug":"sol-b8-rechargeable-battery","sku":"TZ-7PP-B8-SOL","name":"Sol B8 Rechargeable Battery","category":"other"},
  {"slug":"squishies","sku":"TZ-SQSHY","name":"Squishies","category":"other"},
  {"slug":"stash-can","sku":"TZ-STSH-CN","name":"Stash Can","category":"other"},
  {"slug":"t-nation-accessory-pack","sku":"TZ-TNATION PACK","name":"T Nation Accessory Pack","category":"other"},
  {"slug":"tz-sso-pu","sku":"TZ-SSO-PU","name":"TZ SSO Pu","category":"other"},
  {"slug":"wire-case-holder","sku":"TZ-OS-WCH","name":"Wire Case Holder","category":"other"},
];
